export default {
    title: 'Nuevo Empleado',
    route: '/user/signup',
    fields: [
        {
            name: 'nombre',
            type: 'text',
            label: 'Nombre *',
            validate: new RegExp(/^([A-Za-zÁÉÍÓÚáéíóú]+[ ]?){1,2}$/),
            required: true,
            error: false,
            mensaje: '',
            value: '',
        },
        {
            name: 'apellidos',
            type: 'text',
            label: 'Apellidos *',
            validate: new RegExp(/^([A-Za-zÁÉÍÓÚáéíóú]+[ ]?){1,2}$/),
            required: true,
            error: false,
            mensaje: '',
            value: '',
        },
        {
            name: 'telefono',
            type: 'text',
            label: 'Telefono *',
            validate: new RegExp(/^[0-9]{9}$/),
            required: true,
            error: false,
            mensaje: '',
            value: '',
        },
        {
            name: 'email',
            type: 'text',
            label: 'E-Mail *',
            validate: new RegExp(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/),
            required: true,
            error: false,
            mensaje: '',
            value: '',
        },
        {
            name: 'usuario',
            type: 'text',
            label: 'Usuario *',
            validate: null,
            required: true,
            error: false,
            mensaje: '',
            value: '',
        },
        {
            name: 'password',
            type: 'password',
            label: 'Contraseña *',
            validate: null,
            required: true,
            error: false,
            mensaje: '',
            value: '',
        },
        {
            name: 'repeatPassword',
            type: 'password',
            label: 'Repetir contraseña *',
            validate: null,
            required: true,
            error: false,
            mensaje: '',
            value: '',
        },
    ],
    buttons: [
        {
            name: 'Guardar',
            action: 'Save',
            disabled: true
        },
    ],
};